-- Schema cho profile "h2" (in-memory, dùng để chạy thử local)
CREATE TABLE IF NOT EXISTS trade_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    import_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) NOT NULL,
    trade_count INT NOT NULL DEFAULT 0,
    message VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS trade_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket VARCHAR(100) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    volume DECIMAL(18, 2) NOT NULL,
    open_price DECIMAL(18, 5) NOT NULL,
    close_price DECIMAL(18, 5),
    open_time TIMESTAMP NOT NULL,
    close_time TIMESTAMP,
    sl DECIMAL(18, 5),
    tp DECIMAL(18, 5),
    commission DECIMAL(18, 2) DEFAULT 0,
    swap DECIMAL(18, 2) DEFAULT 0,
    profit DECIMAL(18, 2) NOT NULL,
    session_id BIGINT NOT NULL,
    FOREIGN KEY (session_id) REFERENCES trade_sessions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_trade_records_symbol ON trade_records(symbol);
CREATE INDEX IF NOT EXISTS idx_trade_records_session_id ON trade_records(session_id);
CREATE INDEX IF NOT EXISTS idx_trade_records_ticket ON trade_records(ticket);
